---
- name: Add snafu to Foo project
  hosts: localhost
  connection: local
  gather_facts: False
  collections:
    - awx.awx

  tasks:
    - name: Get the ID or Org 2
      set_fact:
        org2id: "{{ lookup('awx.awx.tower_api', 'organizations', query_params={'name': 'Org 2'}, expect_one=True, return_ids=True) }}"

    - name: Add snafu to Foo project use RBAC
      tower_role:
        user: "snafu"
        role: "use"
        project: "{{ lookup('awx.awx.tower_api', 'projects', query_params={'name': 'Foo', 'organization': org2id} , expect_one=True, return_ids=True) }}"
