---
- name: Run Tower Configuration
  hosts: localhost
  gather_facts: False
  vars:
    organizations:
      - "Org 1"
      - "Org 2"
  collections:
    - awx.awx

  tasks:
    - name: Create Organizations
      tower_organization:
        name: "{{ item }}"
      loop: "{{ organizations }}"

    - name: Create Foo Projects
      tower_project:
        name: "Foo"
        organization: "{{ item }}"
        scm_type: 'git'
        scm_url: 'https://github.com/john-westcott-iv/ansiblefest2020'
        scm_branch: devel
        scm_update_on_launch: true
      loop: "{{ organizations }}"

    - name: Configue Tower Settings
      tower_settings:
        settings: "{{ lookup('file', 'files/custom_settings.json') | from_json() }}"

    - name: Create a snafu user
      tower_user:
        username: "snafu"
        first_name: "sna"
        last_name: "fu"
        email: "snafu@example.org"
        password: "snafoo123!"

    - name: "Add snafu user to {{ organizations[0] }}"
      tower_role:
        user: "snafu"
        role: "member"
        organization: "{{ organizations[0] }}"

    - name: Add org1admin user
      tower_user:
        username: "org1admin"
        first_name: "org1"
        last_name: "admin"
        email: "admin@org1.example.org"
        password: "org1admin"

    - name: "Make org1admin an admin of {{ organizations[0] }}"
      tower_role:
        user: "org1admin"
        role: "admin"
        organization: "{{ organizations[0] }}"
      
    - name: Create Export Org
      tower_organization:
        name: "{{ item }}"
      loop:
        - "Export Org"
        - "Production"
        - "Development"

    - name: Create org admins
      tower_user:
        username: "{{ item }}OrgAdmin"
        first_name: "{{ item }}"
        last_name: "OA"
        password: "{{ item }}OrgAdmin123!"
      loop:
        - "Dev"
        - "Prod"

    - name: Assing org admins to org admin role
      tower_role:
        user: "{{ item.short }}OrgAdmin"
        organization: "{{ item.long }}"
        role: "admin"
      loop:
        - short: Dev
          long: Development
        - short: Prod
          long: Production
      loop_control:
        label: "{{ item.short }}"

    - name: Create Tower Credentials for Org Admins
      tower_credential:
        name: "{{ item.short }} Admin Tower Credential"
        organization: "{{ item.long }}"
        credential_type: "Ansible Tower"
        inputs:
          host: "{{ lookup('env', 'TOWER_HOST') }}"
          password: "{{ item.short }}OrgAdmin123!"
          username: "{{ item.short }}OrgAdmin"
      loop:
        - short: Dev
          long: Development
        - short: Prod
          long: Production
      loop_control:
        label: "{{ item.short }}"

    - name: Create Export project
      tower_project:
        name: "Export Project"
        organization: "Export Org"
        scm_type: 'git'
        scm_url: 'https://github.com/john-westcott-iv/ansiblefest2020'
        scm_branch: devel
        scm_update_on_launch: false

    - name: Create Tower Project
      tower_project:
        name: "{{ item }}"
        organization: "{{ item }}"
        scm_type: 'git'
        scm_url: 'https://github.com/john-westcott-iv/ansiblefest2020-awx-lab.git'
        scm_branch: devel
        scm_update_on_launch: true
        scm_branch: "{{ item | lower }}"
      loop:
        - "Production"
        - "Development"

    - name: Create Export Job
      tower_job_template:
        name: "Export Assets"
        project: "Export Project"
        inventory: "Tower Inventory"
        playbook: "export.yml"
        job_type: "run"
        credentials:
          - "Dev Admin Tower Credential"
      register: export_job

    - name: Create Import Job
      tower_job_template:
        name: "Import Assets"
        project: "Export Project"
        inventory: "Tower Inventory"
        playbook: "import.yml"
        job_type: "run"
        credentials:
          - "Prod Admin Tower Credential"
      register: import_job

    - name: Create Export/Import Workflow
      tower_workflow_job_template:
        name: "Migrate Job Templates"
        organization: "Export Org"

    - name: Add import Node
      tower_workflow_job_template_node:
        workflow_job_template: "Migrate Job Templates"
        organization: "Export Org"
        unified_job_template: "{{ import_job.id }}"
        identifier: "import_node"

    - name: Add import Node
      tower_workflow_job_template_node:
        workflow_job_template: "Migrate Job Templates"
        organization: "Export Org"
        unified_job_template: "{{ export_job.id }}"
        success_nodes: "import_node"
        identifier: "export_node"

    - name: Create a dummy job
      tower_job_template:
        name: "The Job"
        project: "Development"
        organization: "Development"
        inventory: "Tower Inventory"
        playbook: "demo.yml"
        job_type: "run"
      register: the_job

    - name: Create a developer user
      tower_user:
        username: "dev"
        first_name: "Jane"
        last_name: "Developer"
        password: "dev123!"

    - name: Create an operations user
      tower_user:
        username: "ops"
        first_name: "Joe"
        last_name: "Operator"
        password: "ops123!"

    - name: Give developer modify perms on Demo Job template
      tower_role:
        user: "dev"
        role: "admin"
        job_template: "{{ the_job.id }}"

    - name: Give developer execute perms on Migrate Job Templates
      tower_role:
        user: "dev"
        role: "execute"
        workflow: "Migrate Job Templates"

    - name: Give users use access to the Tower Inventory
      tower_role:
        user: "{{ item }}"
        inventory: "Tower Inventory"
        role: "use"
      loop:
        - "dev"
        - "ProdOrgAdmin"

    - name: Give the developer use access to the Development project
      tower_role:
        user: "dev"
        project: "Development"
        role: "use"
