---
- name: Import job templates
  hosts: localhost
  connection: local
  gather_facts: False
  collections:
    - awx.awx

  tasks:
    - name: "Import Job Templates Into Production"
      tower_job_template:
        name: "{{ item.name | default(omit) }}"
        description: "{{ item.description | default(omit) }}"
        job_type: "{{ item.job_type | default(omit) }}"
        inventory: "{{ item.inventory | default(omit) }}"
        project: "Production"
        playbook: "{{ item.playbook | default(omit) }}"
        credentials: "{{ credential_ids | default(omit) }}"
        forks: "{{ item.forks | default(omit) }}"
        limit: "{{ item.limit | default(omit) }}"
        verbosity: "{{ item.verbosity | default(omit) }}"
        extra_vars: "{{ item.extra_vars | to_json() | default({}) | combine({ 'environment': 'prod' }) }}"
        job_tags: "{{ item.job_tags | default(omit) }}"
        force_handlers: "{{ item.force_handlers | default(omit) }}"
        skip_tags: "{{ item.skip_tags | default(omit) }}"
        start_at_task: "{{ item.start_at_task | default(omit) }}"
        diff_mode: "{{ item.diff_mode | default(omit) }}"
        use_fact_cache: "{{ item.use_fact_cache | default(omit) }}"
        host_config_key: "{{ item.host_config_key | default(omit) }}"
        ask_scm_branch_on_launch: "{{ item.ask_scm_branch_on_launch | default(omit) }}"
        ask_diff_mode_on_launch: "{{ item.ask_diff_mode_on_launch | default(omit) }}"
        ask_variables_on_launch: "{{ item.ask_variables_on_launch | default(omit) }}"
        ask_limit_on_launch: "{{ item.ask_limit_on_launch | default(omit) }}"
        ask_tags_on_launch: "{{ item.ask_tags_on_launch | default(omit) }}"
        ask_skip_tags_on_launch: "{{ item.ask_skip_tags_on_launch | default(omit) }}"
        ask_job_type_on_launch: "{{ item.ask_job_type_on_launch | default(omit) }}"
        ask_verbosity_on_launch: "{{ item.ask_verbosity_on_launch | default(omit) }}"
        ask_inventory_on_launch: "{{ item.ask_inventory_on_launch | default(omit) }}"
        ask_credential_on_launch: "{{ item.ask_credential_on_launch | default(omit) }}"
        survey_enabled: "{{ item.survey_enabled | default(omit) }}"
        survey_spec: "{{ survey_specs[ item.id ] | default(omit) }}"
        become_enabled: "{{ item.become_enabled | default(omit) }}"
        allow_simultaneous: "{{ item.allow_simultaneous | default(omit) }}"
        timeout: "{{ item.timeout | default(omit) }}"
        custom_virtualenv: "{{ item.custom_virtualenv | default(omit) }}"
        job_slice_count: "{{ item.job_slice_count | default(omit) }}"
        webhook_service: "{{ item.webhook_service | default(omit) }}"
        webhook_credential: "{{ item.webhook_credential | default(omit) }}"
        scm_branch: "{{ item.scm_branch | default(omit) }}"
        labels: "{{ item.labels | default(omit) }}"
      loop: "{{ job_templates }}"
      vars:
        credential_ids: "{{ item.summary_fields.credentials | json_query('[*].id') }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Give ops user permissions to execute our job
      tower_role:
        user: ops
        role: execute
        job_template: "{{ item.name }}"
      loop: "{{ job_templates }}"
      loop_control:
        label: "{{ item.name }}"
