---
- name: Customize My Tower Instance
  hosts: localhost
  connection: local
  gather_facts: False
  collections:
    - awx.awx

  tasks:
    - name: Set my login message
      awx.awx.tower_settings:
        name: "CUSTOM_LOGIN_INFO"
        value: "This is my own Tower instance"

